export const CAMERA_LIMITS = {
  NEAR: 0.1,
  FAR: 1000,
} as const;

export const CAMERA_ANIMATION = {
  PRESET: 700,
  BOOKMARK: 900,
} as const;

export const CAMERA_ANIMATOR = {
  FOV: 50,
  POSITION_Z: 8,
  MOVE_DURATION: 600,
  LOOK_DURATION: 600,
  FOV_DURATION: 350,
  LERP_FACTOR: 0.06,
  FOV_LERP_FACTOR: 0.1,
  FOV_THRESHOLD: 0.01,
  RESUME_TRANSITION_MS: 400,
  BLEND_FACTOR: 0.25,
  EASING_POWER: 2.5,
  DELTA_MULTIPLIER: 6,
  EPSILON: 0.0001,
  PROGRESS_THRESHOLD: 0.01,
} as const;

export const PERSPECTIVE_ORTHO = {
  DEFAULT_FOV: 55,
  BASE_ZOOM: 20,
  FOV_MIN: 10,
  FOV_MAX: 120,
  DEG_TO_RAD_HALF: 180,
  REFERENCE_DISTANCE: 9,
  REFERENCE_HEIGHT: 10,
} as const;

export const CAMERA_TRANSITION = {
  EPSILON: 0.0001,
  ABOVE_Z_OFFSET: 0.1,
  MODE_DURATION: 400,
} as const;
