export const ANIME_DEFAULTS = {
  SHADOW_STEPS: 4,
  SHADOW_THRESHOLD: 0.45,
  HIGHLIGHT_SHARPNESS: 0.8,
  OUTLINE_WIDTH: 1.2,
  OUTLINE_COLOR_R: 0.1,
  OUTLINE_COLOR_G: 0.08,
  OUTLINE_COLOR_B: 0.05,
  SKIN_TONE_BOOST: 0.4,
} as const;

export const CEL_DEFAULTS = {
  COLOR_BANDS: 4,
  OUTLINE_THICKNESS: 1.8,
  OUTLINE_COLOR_R: 0.05,
  OUTLINE_COLOR_G: 0.03,
  OUTLINE_COLOR_B: 0.02,
  SHADOW_COLOR_R: 0.15,
  SHADOW_COLOR_G: 0.15,
  SHADOW_COLOR_B: 0.25,
  HALFTONE_SIZE: 2.0,
  SPECULAR_SIZE: 0.35,
} as const;

export const CRYSTAL_DEFAULTS = {
  IOR: 1.45,
  DISPERSION: 0.025,
  FRESNEL_POWER: 2.8,
  TRANSMISSION: 0.92,
  CAUSTICS: 0.5,
  CRYSTAL_COLOR_R: 0.88,
  CRYSTAL_COLOR_G: 0.93,
  CRYSTAL_COLOR_B: 1.0,
} as const;

export const HOLOGRAM_V2_DEFAULTS = {
  SCANLINE_INTENSITY: 0.5,
  SCANLINE_DENSITY: 60.0,
  RGB_OFFSET: 0.004,
  FLICKER_SPEED: 1.5,
  GLITCH_INTENSITY: 0.25,
  FRESNEL_POWER: 2.2,
  HOLO_COLOR_R: 0.1,
  HOLO_COLOR_G: 0.9,
  HOLO_COLOR_B: 1.0,
  DATA_STREAM_SPEED: 1.2,
} as const;

export const INK_WASH_DEFAULTS = {
  INK_DENSITY: 0.75,
  BLEED_AMOUNT: 0.6,
  PAPER_TEXTURE: 0.5,
  BRUSH_TEXTURE: 0.7,
  WHITE_SPACE: 0.35,
  EDGE_WOBBLE: 0.35,
} as const;

export const MATRIX_DEFAULTS = {
  FALL_SPEED: 1.8,
  CHAR_DENSITY: 0.7,
  GLOW_INTENSITY: 1.4,
  TRAIL_LENGTH: 0.6,
  MATRIX_COLOR_R: 0.05,
  MATRIX_COLOR_G: 1.0,
  MATRIX_COLOR_B: 0.85,
  CHAR_SIZE: 10.0,
  SHOW_ORIGINAL: 0.4,
} as const;

export const NORMAL_DEFAULTS = {
  BRIGHTNESS: 1.02,
  CONTRAST: 1.05,
  SATURATION: 1.08,
} as const;

export const RETRO_PIXEL_DEFAULTS = {
  PIXEL_SIZE: 3.0,
  PALETTE_MODE: 1,
  DITHER_STRENGTH: 0.45,
  CRT_EFFECT: 0.25,
  COLOR_DEPTH: 24,
  SCANLINE_BRIGHTNESS: 0.9,
} as const;

export const UNIFORM_DEFAULTS = {
  ZERO: 0.0,
  ONE: 1.0,
  OPACITY_DEFAULT: 1.0,
  EDGE_FADE_DEFAULT: 0.75,
  SEAM_CORRECTION_DEFAULT: 0.0,
  DISPLACEMENT_SCALE_DEFAULT: 0.0,
  DISPLACEMENT_BIAS_DEFAULT: 0.0,
} as const;

export const TEXTURE = {
  DEFAULT_TEXEL_SIZE: 1024,
} as const;
